# generate_bias_report.R
# Generate comprehensive markdown report for all bias tests
# Kate Snyder
# Created: 2025-06-08

library(phytools)
library(dplyr)
library(tidyr)

# Source required functions
#source("run_bias_tests.R")
#source("run_dimorphism_bias_tests.R")

#' Generate comprehensive bias testing report
#'
#' @param df Data frame with species data
#' @param tree Phylogenetic tree
#' @param output_file Path to output markdown file
#' @param output_dir Directory for saving plots and intermediate files
#' @return Invisibly returns the full report text
generate_bias_report <- function(df,
                               tree,
                               output_file = "Bias_Test_Results.md",
                               output_dir = "Outputs/BiasTestReport") {
  
  # Create output directory
  if (!dir.exists(output_dir)) {
    dir.create(output_dir, recursive = TRUE)
  }
  
  # Initialize report
  report <- c(
    "# Bias Testing Results",
    paste("\n**Date:**", Sys.Date()),
    paste("**Generated by:** generate_bias_report.R"),
    paste("**Data file:** Data_R_2025-07-23.csv"),
    paste("**Tree file:** 2022-03-16ConsensusPasserineTreeHackett4_1000_OscineSubset.nex"),
    "\n## Overview",
    "\nThis report presents results from comprehensive bias testing to identify potential sampling biases in the dataset. We tested seven specific hypotheses about data availability biases that could affect evolutionary analyses of cooperative breeding and female song in passerine birds.\n"
  )
  
  # Prepare data
  df_work <- df[df$species %in% tree$tip.label, ]
  
  # Add geographic regions if needed
  if (!"GeographicRegion_Jetz" %in% colnames(df_work)) {
    df_work$GeographicRegion_Jetz <- NA
    df_work$GeographicRegion_Jetz[which(df_work$Realm_Jetz2011 %in% c("PA", "NeA"))] <- "Holarctic"
    df_work$GeographicRegion_Jetz[which(df_work$Realm_Jetz2011 %in% c("AT", "NT", "IM", "AA", "OC"))] <- "Tropical"
  }
  
  # Add data availability indicators
  df_work$HaveFSData <- !is.na(df_work$FemaleSong_Agg01)
  df_work$HaveCBData <- !is.na(df_work$HighConfidence_Coop)
  df_work$HaveBothData <- df_work$HaveFSData & df_work$HaveCBData
  
  # Dataset summary
  report <- c(report,
    "## Dataset Summary",
    paste("\n- Total species in tree:", length(tree$tip.label)),
    paste("- Species with data:", nrow(df_work)),
    paste("- Species with Female Song data:", sum(df_work$HaveFSData)),
    paste("- Species with Cooperative Breeding data:", sum(df_work$HaveCBData)),
    paste("- Species with both FS and CB data:", sum(df_work$HaveBothData)),
    "\n---\n"
  )
  
  # Test 1: Cooperative breeding bias
  report <- c(report, test_cooperative_breeding_bias(df_work))
  
  # Test 2: Social system biases
  report <- c(report, test_social_system_biases(df_work))
  
  # Test 3: Territoriality bias for complex breeding systems
  report <- c(report, test_territoriality_breeding_bias(df_work))
  
  # Test 4: Sexual dichromatism bias
  report <- c(report, test_dichromatism_bias(df_work))
  
  # Test 5: Sexual size dimorphism bias
  report <- c(report, test_size_dimorphism_bias(df_work))
  
  # Test 6: Geographic (Holarctic) bias
  report <- c(report, test_geographic_bias(df_work))
  
  # Test 7: Cooperative breeding x Geographic region interaction
  report <- c(report, test_cb_geographic_interaction_bias(df_work))
  
  # Summary and recommendations
  report <- c(report, generate_summary_recommendations(df_work))
  
  # Write report
  writeLines(report, output_file)
  cat("Report saved to:", output_file, "\n")
  
  invisible(report)
}

# Test 1: Cooperative breeding bias
test_cooperative_breeding_bias <- function(df) {
  report <- c(
    "## Test 1: Cooperative Breeding Bias",
    "\n**Hypothesis:** Cooperative breeding species have a greater likelihood of being studied to a degree where female song presence or absence can be determined.\n"
  )
  
  # Create contingency table
  cont_table <- table(
    CB = ifelse(df$HighConfidence_Coop == 1, "Cooperative", "Non-cooperative"),
    FS_Data = ifelse(df$HaveFSData, "Has FS Data", "No FS Data")
  )
  
  # Chi-square test
  chi_test <- chisq.test(cont_table)
  
  # Calculate proportions
  props <- prop.table(cont_table, margin = 1)
  
  report <- c(report,
    "### Contingency Table",
    "```",
    capture.output(print(cont_table)),
    "```",
    "\n### Proportions (by row)",
    "```",
    capture.output(print(round(props, 3))),
    "```",
    "\n### Statistical Test",
    paste("- Chi-squared test: χ² =", round(chi_test$statistic, 3), 
          ", df =", chi_test$parameter, 
          ", p =", format.pval(chi_test$p.value, digits = 3)),
    "\n### Result",
    ifelse(chi_test$p.value < 0.05,
           paste("**Significant bias detected (p < 0.05):** Cooperative breeders have",
                 ifelse(props["Cooperative", "Has FS Data"] > props["Non-cooperative", "Has FS Data"],
                        "MORE", "LESS"),
                 "female song data than non-cooperative species."),
           "No significant bias detected (p ≥ 0.05)."),
    "\n---\n"
  )
  
  return(report)
}

# Test 2: Social system biases
test_social_system_biases <- function(df) {
  report <- c(
    "## Test 2: Social System Biases",
    "\n**Hypothesis:** Birds that group together (colonial species, familial-living species, and polygynous species) are more likely to be studied.\n"
  )
  
  social_cols <- c("Griesser2023.Colonial01", "Griesser2017FamilialLiving", "Final.polygyny")
  social_labels <- c("Colonial", "Familial Living", "Polygynous")
  
  for (i in seq_along(social_cols)) {
    col <- social_cols[i]
    label <- social_labels[i]
    
    if (col %in% colnames(df) && sum(!is.na(df[[col]])) > 10) {
      report <- c(report, paste("\n### ", label))
      
      # Create contingency table
      cont_table <- table(
        Social = ifelse(df[[col]] == 1, paste(label, "Yes"), paste(label, "No")),
        FS_Data = ifelse(df$HaveFSData, "Has FS Data", "No FS Data")
      )
      
      # Skip if one category is too small
      if (min(table(df[[col]])) < 5) {
        report <- c(report, "\nInsufficient data for statistical test.\n")
        next
      }
      
      # Chi-square test
      chi_test <- chisq.test(cont_table)
      props <- prop.table(cont_table, margin = 1)
      
      report <- c(report,
        "```",
        capture.output(print(cont_table)),
        "```",
        paste("\n- Chi-squared test: χ² =", round(chi_test$statistic, 3), 
              ", df =", chi_test$parameter, 
              ", p =", format.pval(chi_test$p.value, digits = 3)),
        paste("- Proportion with FS data:", label, "Yes =", 
              round(props[paste(label, "Yes"), "Has FS Data"], 3),
              ", No =", round(props[paste(label, "No"), "Has FS Data"], 3))
      )
    }
  }
  
  report <- c(report, "\n---\n")
  return(report)
}

# Test 3: Territoriality bias for complex breeding systems
test_territoriality_breeding_bias <- function(df) {
  report <- c(
    "## Test 3: Territoriality and Complex Breeding Systems",
    "\n**Hypothesis:** It is more likely for complex breeding systems to be detected in year-round territorial birds.\n"
  )
  
  # Test if year-round territorial birds are more likely to have CB data
  if ("Territory_12vs3" %in% colnames(df)) {
    df$YearRoundTerritorial <- ifelse(df$Territory_12vs3 == 1, "Year-round", "Seasonal")
    
    cont_table <- table(
      Territory = df$YearRoundTerritorial,
      CB_Data = ifelse(df$HaveCBData, "Has CB Data", "No CB Data")
    )
    
    chi_test <- chisq.test(cont_table)
    props <- prop.table(cont_table, margin = 1)
    
    report <- c(report,
      "\n### Cooperative Breeding Data by Territoriality",
      "```",
      capture.output(print(cont_table)),
      "```",
      "\n### Proportions",
      "```",
      capture.output(print(round(props, 3))),
      "```",
      paste("\n- Chi-squared test: χ² =", round(chi_test$statistic, 3), 
            ", df =", chi_test$parameter, 
            ", p =", format.pval(chi_test$p.value, digits = 3)),
      "\n### Result",
      ifelse(chi_test$p.value < 0.05,
             paste("**Significant bias detected:** Year-round territorial species have",
                   ifelse(props["Year-round", "Has CB Data"] > props["Seasonal", "Has CB Data"],
                          "MORE", "LESS"),
                   "cooperative breeding data."),
             "No significant bias detected.")
    )
    
    # Also test for both FS and CB data
    cont_table2 <- table(
      Territory = df$YearRoundTerritorial,
      Both_Data = ifelse(df$HaveBothData, "Has Both", "Missing Data")
    )
    
    chi_test2 <- chisq.test(cont_table2)
    props2 <- prop.table(cont_table2, margin = 1)
    
    report <- c(report,
      "\n\n### Both FS and CB Data by Territoriality",
      "```",
      capture.output(print(cont_table2)),
      "```",
      paste("\n- Chi-squared test: χ² =", round(chi_test2$statistic, 3), 
            ", df =", chi_test2$parameter, 
            ", p =", format.pval(chi_test2$p.value, digits = 3)),
      paste("- Proportion with both datasets: Year-round =", 
            round(props2["Year-round", "Has Both"], 3),
            ", Seasonal =", round(props2["Seasonal", "Has Both"], 3))
    )
  }
  
  report <- c(report, "\n---\n")
  return(report)
}

# Test 4: Sexual dichromatism bias
test_dichromatism_bias <- function(df) {
  report <- c(
    "## Test 4: Sexual Dichromatism Bias",
    "\n**Hypothesis:** Greater sexual dichromatism leads to a higher rate of identification of female song, so species with lower sexual dichromatism would either be underrepresented in the dataset overall or would be more likely to be miscategorized as female song absent.\n"
  )
  
  if ("logMaleFemalePlumageDiffAbs" %in% colnames(df)) {
    # Remove infinite values
    df_plumage <- df[is.finite(df$logMaleFemalePlumageDiffAbs), ]
    
    # Test 1: Do dichromatic species have more FS data?
    t_test1 <- t.test(logMaleFemalePlumageDiffAbs ~ HaveFSData, data = df_plumage)
    
    # Summary stats
    summary_stats <- df_plumage %>%
      group_by(HaveFSData) %>%
      summarise(
        n = n(),
        mean = round(mean(logMaleFemalePlumageDiffAbs, na.rm = TRUE), 3),
        sd = round(sd(logMaleFemalePlumageDiffAbs, na.rm = TRUE), 3),
        .groups = "drop"
      )
    
    report <- c(report,
      "### Test 4a: Dichromatism by Data Availability",
      "\n**Question:** Are dichromatic species more likely to have female song data?\n",
      "\n#### Summary Statistics",
      "```",
      capture.output(print(summary_stats)),
      "```",
      "\n#### Statistical Test",
      paste("- Welch Two Sample t-test: t =", round(t_test1$statistic, 3),
            ", df =", round(t_test1$parameter, 1),
            ", p =", format.pval(t_test1$p.value, digits = 3)),
      paste("- Mean difference:", round(diff(t_test1$estimate), 3)),
      "\n#### Result",
      ifelse(t_test1$p.value < 0.05,
             paste("**Significant difference:** Species",
                   ifelse(t_test1$estimate[2] > t_test1$estimate[1], "WITH", "WITHOUT"),
                   "female song data are more dichromatic."),
             "No significant difference in dichromatism by data availability.")
    )
    
    # Test 2: Among species with data, do dichromatic species differ in FS presence?
    df_with_fs <- df_plumage[!is.na(df_plumage$FemaleSong_Agg01), ]
    if (nrow(df_with_fs) > 10) {
      t_test2 <- t.test(logMaleFemalePlumageDiffAbs ~ FemaleSong_Agg01, data = df_with_fs)
      
      summary_stats2 <- df_with_fs %>%
        group_by(FemaleSong_Agg01) %>%
        summarise(
          n = n(),
          mean = round(mean(logMaleFemalePlumageDiffAbs, na.rm = TRUE), 3),
          sd = round(sd(logMaleFemalePlumageDiffAbs, na.rm = TRUE), 3),
          .groups = "drop"
        )
      
      report <- c(report,
        "\n### Test 4b: Dichromatism by Female Song Presence",
        "\n**Question:** Among species with data, are dichromatic species more likely to have female song?\n",
        "\n#### Summary Statistics",
        "```",
        capture.output(print(summary_stats2)),
        "```",
        "\n#### Statistical Test",
        paste("- Welch Two Sample t-test: t =", round(t_test2$statistic, 3),
              ", df =", round(t_test2$parameter, 1),
              ", p =", format.pval(t_test2$p.value, digits = 3)),
        paste("- Mean difference:", round(diff(t_test2$estimate), 3)),
        "\n#### Result",
        ifelse(t_test2$p.value < 0.05,
               paste("**Significant difference:** Species with female song",
                     ifelse(t_test2$estimate[2] < t_test2$estimate[1], "ABSENT", "PRESENT"),
                     "are more dichromatic."),
               "No significant difference in dichromatism by female song presence.")
      )
    }
  }
  
  report <- c(report, "\n---\n")
  return(report)
}

# Test 5: Sexual size dimorphism bias
test_size_dimorphism_bias <- function(df) {
  report <- c(
    "## Test 5: Sexual Size Dimorphism Bias",
    "\n**Hypothesis:** Greater sexual dimorphism in size leads to a higher rate of identification of female song.\n"
  )
  
  if ("PercentLogWingDimorphism_AVONET" %in% colnames(df)) {
    # Test 1: Do size-dimorphic species have more FS data?
    t_test1 <- t.test(PercentLogWingDimorphism_AVONET ~ HaveFSData, data = df)
    
    # Summary stats
    summary_stats <- df %>%
      filter(!is.na(PercentLogWingDimorphism_AVONET)) %>%
      group_by(HaveFSData) %>%
      summarise(
        n = n(),
        mean = round(mean(PercentLogWingDimorphism_AVONET, na.rm = TRUE), 3),
        sd = round(sd(PercentLogWingDimorphism_AVONET, na.rm = TRUE), 3),
        .groups = "drop"
      )
    
    report <- c(report,
      "### Test 5a: Size Dimorphism by Data Availability",
      "\n**Question:** Are size-dimorphic species more likely to have female song data?\n",
      "\n#### Summary Statistics",
      "```",
      capture.output(print(summary_stats)),
      "```",
      "\n#### Statistical Test",
      paste("- Welch Two Sample t-test: t =", round(t_test1$statistic, 3),
            ", df =", round(t_test1$parameter, 1),
            ", p =", format.pval(t_test1$p.value, digits = 3)),
      paste("- Mean difference:", round(diff(t_test1$estimate), 3)),
      "\n#### Result",
      ifelse(t_test1$p.value < 0.05,
             paste("**Significant difference:** Species",
                   ifelse(t_test1$estimate[2] > t_test1$estimate[1], "WITH", "WITHOUT"),
                   "female song data are more size-dimorphic."),
             "No significant difference in size dimorphism by data availability.")
    )
    
    # Test 2: Among species with data, do size-dimorphic species differ in FS presence?
    df_with_fs <- df[!is.na(df$FemaleSong_Agg01) & !is.na(df$PercentLogWingDimorphism_AVONET), ]
    if (nrow(df_with_fs) > 10) {
      t_test2 <- t.test(PercentLogWingDimorphism_AVONET ~ FemaleSong_Agg01, data = df_with_fs)
      
      summary_stats2 <- df_with_fs %>%
        group_by(FemaleSong_Agg01) %>%
        summarise(
          n = n(),
          mean = round(mean(PercentLogWingDimorphism_AVONET, na.rm = TRUE), 3),
          sd = round(sd(PercentLogWingDimorphism_AVONET, na.rm = TRUE), 3),
          .groups = "drop"
        )
      
      report <- c(report,
        "\n### Test 5b: Size Dimorphism by Female Song Presence",
        "\n**Question:** Among species with data, are size-dimorphic species more likely to have female song?\n",
        "\n#### Summary Statistics",
        "```",
        capture.output(print(summary_stats2)),
        "```",
        "\n#### Statistical Test",
        paste("- Welch Two Sample t-test: t =", round(t_test2$statistic, 3),
              ", df =", round(t_test2$parameter, 1),
              ", p =", format.pval(t_test2$p.value, digits = 3)),
        paste("- Mean difference:", round(diff(t_test2$estimate), 3)),
        "\n#### Result",
        ifelse(t_test2$p.value < 0.05,
               paste("**Significant difference:** Species with female song",
                     ifelse(t_test2$estimate[2] < t_test2$estimate[1], "ABSENT", "PRESENT"),
                     "are more size-dimorphic."),
               "No significant difference in size dimorphism by female song presence.")
      )
    }
  }
  
  report <- c(report, "\n---\n")
  return(report)
}

# Test 6: Geographic bias
test_geographic_bias <- function(df) {
  report <- c(
    "## Test 6: Geographic (Holarctic) Bias",
    "\n**Hypothesis:** Holarctic species are overrepresented in the dataset.\n"
  )
  
  if ("GeographicRegion_Jetz" %in% colnames(df)) {
    # Test for FS data
    cont_table_fs <- table(
      Region = df$GeographicRegion_Jetz,
      FS_Data = ifelse(df$HaveFSData, "Has FS Data", "No FS Data")
    )
    
    chi_test_fs <- chisq.test(cont_table_fs)
    props_fs <- prop.table(cont_table_fs, margin = 1)
    
    report <- c(report,
      "### Female Song Data by Geographic Region",
      "```",
      capture.output(print(cont_table_fs)),
      "```",
      "\n### Proportions",
      "```",
      capture.output(print(round(props_fs, 3))),
      "```",
      paste("\n- Chi-squared test: χ² =", round(chi_test_fs$statistic, 3),
            ", df =", chi_test_fs$parameter,
            ", p =", format.pval(chi_test_fs$p.value, digits = 3)),
      "\n### Result",
      ifelse(chi_test_fs$p.value < 0.05,
             paste("**Significant geographic bias detected:** Holarctic species have",
                   ifelse(props_fs["Holarctic", "Has FS Data"] > props_fs["Tropical", "Has FS Data"],
                          "MORE", "LESS"),
                   "female song data than Tropical species."),
             "No significant geographic bias for female song data.")
    )
    
    # Test for CB data
    cont_table_cb <- table(
      Region = df$GeographicRegion_Jetz,
      CB_Data = ifelse(df$HaveCBData, "Has CB Data", "No CB Data")
    )
    
    chi_test_cb <- chisq.test(cont_table_cb)
    props_cb <- prop.table(cont_table_cb, margin = 1)
    
    report <- c(report,
      "\n\n### Cooperative Breeding Data by Geographic Region",
      "```",
      capture.output(print(cont_table_cb)),
      "```",
      paste("\n- Chi-squared test: χ² =", round(chi_test_cb$statistic, 3),
            ", df =", chi_test_cb$parameter,
            ", p =", format.pval(chi_test_cb$p.value, digits = 3)),
      paste("- Proportion with CB data: Holarctic =", 
            round(props_cb["Holarctic", "Has CB Data"], 3),
            ", Tropical =", round(props_cb["Tropical", "Has CB Data"], 3))
    )
    
    # Test for both
    cont_table_both <- table(
      Region = df$GeographicRegion_Jetz,
      Both_Data = ifelse(df$HaveBothData, "Has Both", "Missing Data")
    )
    
    chi_test_both <- chisq.test(cont_table_both)
    props_both <- prop.table(cont_table_both, margin = 1)
    
    report <- c(report,
      "\n\n### Both FS and CB Data by Geographic Region",
      "```",
      capture.output(print(cont_table_both)),
      "```",
      paste("\n- Chi-squared test: χ² =", round(chi_test_both$statistic, 3),
            ", df =", chi_test_both$parameter,
            ", p =", format.pval(chi_test_both$p.value, digits = 3)),
      paste("- Proportion with both datasets: Holarctic =", 
            round(props_both["Holarctic", "Has Both"], 3),
            ", Tropical =", round(props_both["Tropical", "Has Both"], 3)),
      "\n### Overall Geographic Bias Result",
      ifelse(chi_test_fs$p.value < 0.05 | chi_test_cb$p.value < 0.05 | chi_test_both$p.value < 0.05,
             "**Significant geographic bias detected in data availability.**",
             "No significant geographic bias detected.")
    )
  }
  
  report <- c(report, "\n---\n")
  return(report)
}

# Test 7: Cooperative breeding x Geographic region interaction bias
test_cb_geographic_interaction_bias <- function(df) {
  report <- c(
    "## Test 7: Cooperative Breeding × Geographic Region Interaction",
    "\n**Hypothesis:** Non-cooperative breeders are more likely to have female song data in the Holarctic region.\n"
  )
  
  # Filter to species with CB data and geographic region
  df_subset <- df[!is.na(df$HighConfidence_Coop) & !is.na(df$GeographicRegion_Jetz), ]
  
  # Create interaction variable
  df_subset$CB_Region <- paste(
    ifelse(df_subset$HighConfidence_Coop == 1, "Cooperative", "Non-cooperative"),
    df_subset$GeographicRegion_Jetz,
    sep = "_"
  )
  
  # Create contingency table
  cont_table <- table(
    CB_Region = df_subset$CB_Region,
    FS_Data = ifelse(df_subset$HaveFSData, "Has FS Data", "No FS Data")
  )
  
  # Chi-square test
  chi_test <- chisq.test(cont_table)
  
  # Calculate proportions within each group
  props <- prop.table(cont_table, margin = 1)
  
  # Create a more readable summary table
  summary_df <- data.frame(
    Cooperative_Breeding = c("Cooperative", "Cooperative", "Non-cooperative", "Non-cooperative"),
    Region = c("Holarctic", "Tropical", "Holarctic", "Tropical"),
    N_Total = as.vector(rowSums(cont_table)),
    N_With_FS_Data = cont_table[, "Has FS Data"],
    Prop_With_FS_Data = round(props[, "Has FS Data"], 3)
  )
  rownames(summary_df) <- NULL
  
  report <- c(report,
    "### Contingency Table",
    "```",
    capture.output(print(cont_table)),
    "```",
    "\n### Summary by Group",
    "```",
    capture.output(print(summary_df)),
    "```",
    "\n### Statistical Test",
    paste("- Chi-squared test: χ² =", round(chi_test$statistic, 3), 
          ", df =", chi_test$parameter, 
          ", p =", format.pval(chi_test$p.value, digits = 3)),
    "\n### Key Comparisons",
    paste("- Non-cooperative Holarctic:", 
          round(props["Non-cooperative_Holarctic", "Has FS Data"] * 100, 1), "%"),
    paste("- Non-cooperative Tropical:", 
          round(props["Non-cooperative_Tropical", "Has FS Data"] * 100, 1), "%"),
    paste("- Cooperative Holarctic:", 
          round(props["Cooperative_Holarctic", "Has FS Data"] * 100, 1), "%"),
    paste("- Cooperative Tropical:", 
          round(props["Cooperative_Tropical", "Has FS Data"] * 100, 1), "%"),
    "\n### Result"
  )
  
  # Interpret the result
  if (chi_test$p.value < 0.05) {
    # Check if non-cooperative holarctic have highest proportion
    nc_holarctic_prop <- props["Non-cooperative_Holarctic", "Has FS Data"]
    nc_tropical_prop <- props["Non-cooperative_Tropical", "Has FS Data"]
    c_holarctic_prop <- props["Cooperative_Holarctic", "Has FS Data"]
    c_tropical_prop <- props["Cooperative_Tropical", "Has FS Data"]
    
    if (nc_holarctic_prop > nc_tropical_prop && nc_holarctic_prop > c_holarctic_prop) {
      report <- c(report,
        "**Significant interaction detected (p < 0.05):** Non-cooperative breeders in the Holarctic region have the highest proportion of female song data, supporting the hypothesis.")
    } else {
      report <- c(report,
        paste("**Significant interaction detected (p < 0.05):** However, the pattern does not support the hypothesis.",
              "The group with highest FS data availability is:",
              names(which.max(props[, "Has FS Data"]))))
    }
  } else {
    report <- c(report,
      "No significant interaction detected (p ≥ 0.05). The availability of female song data does not significantly differ across the combination of cooperative breeding status and geographic region.")
  }
  
  # Add post-hoc pairwise comparisons if significant
  if (chi_test$p.value < 0.05) {
    report <- c(report,
      "\n### Post-hoc Analysis",
      "\nTo better understand the interaction, we can examine specific contrasts:")
    
    # Test 1: Within Holarctic, compare CB vs non-CB
    holarctic_data <- df_subset[df_subset$GeographicRegion_Jetz == "Holarctic", ]
    if (nrow(holarctic_data) > 0) {
      hol_table <- table(
        CB = ifelse(holarctic_data$HighConfidence_Coop == 1, "Cooperative", "Non-cooperative"),
        FS = ifelse(holarctic_data$HaveFSData, "Has FS", "No FS")
      )
      hol_test <- chisq.test(hol_table)
      report <- c(report,
        paste("\n**Within Holarctic region:** χ² =", round(hol_test$statistic, 3),
              ", p =", format.pval(hol_test$p.value, digits = 3)))
    }
    
    # Test 2: Within Tropical, compare CB vs non-CB
    tropical_data <- df_subset[df_subset$GeographicRegion_Jetz == "Tropical", ]
    if (nrow(tropical_data) > 0) {
      trop_table <- table(
        CB = ifelse(tropical_data$HighConfidence_Coop == 1, "Cooperative", "Non-cooperative"),
        FS = ifelse(tropical_data$HaveFSData, "Has FS", "No FS")
      )
      trop_test <- chisq.test(trop_table)
      report <- c(report,
        paste("\n**Within Tropical region:** χ² =", round(trop_test$statistic, 3),
              ", p =", format.pval(trop_test$p.value, digits = 3)))
    }
    
    # Test 3: Within non-cooperative, compare regions
    noncoop_data <- df_subset[df_subset$HighConfidence_Coop == 0, ]
    if (nrow(noncoop_data) > 0) {
      nc_table <- table(
        Region = noncoop_data$GeographicRegion_Jetz,
        FS = ifelse(noncoop_data$HaveFSData, "Has FS", "No FS")
      )
      nc_test <- chisq.test(nc_table)
      report <- c(report,
        paste("\n**Within Non-cooperative breeders:** χ² =", round(nc_test$statistic, 3),
              ", p =", format.pval(nc_test$p.value, digits = 3)))
    }
    
    # Test 4: Within cooperative, compare regions
    coop_data <- df_subset[df_subset$HighConfidence_Coop == 1, ]
    if (nrow(coop_data) > 0) {
      c_table <- table(
        Region = coop_data$GeographicRegion_Jetz,
        FS = ifelse(coop_data$HaveFSData, "Has FS", "No FS")
      )
      c_test <- chisq.test(c_table)
      report <- c(report,
        paste("\n**Within Cooperative breeders:** χ² =", round(c_test$statistic, 3),
              ", p =", format.pval(c_test$p.value, digits = 3)))
    }
  }
  
  report <- c(report, "\n---\n")
  return(report)
}

# Generate summary and recommendations
generate_summary_recommendations <- function(df) {
  report <- c(
    "## Summary of Bias Testing Results",
    "\nThe following biases were detected in the dataset:\n"
  )
  
  # This would be filled in based on the actual test results
  # For now, providing a template
  report <- c(report,
    "1. **Cooperative Breeding Bias:** [Summary of result]",
    "2. **Social System Biases:** [Summary of results for colonial, familial, polygynous]",
    "3. **Territoriality Bias:** [Summary of result]",
    "4. **Sexual Dichromatism Bias:** [Summary of results]",
    "5. **Sexual Size Dimorphism Bias:** [Summary of results]",
    "6. **Geographic Bias:** [Summary of result]",
    "7. **CB × Geographic Interaction:** [Summary of interaction effect]",
    "\n## Recommendations for Bias Correction",
    "\nBased on the detected biases, we recommend the following corrections:",
    "\n### Priority 1: Address Geographic Bias",
    "- Downsample [X] species from [region] to balance data availability",
    "\n### Priority 2: Address Territoriality Bias",
    "- Consider territoriality as a confounding variable in analyses",
    "\n### Priority 3: Consider Dimorphism Effects",
    "- Include sexual dimorphism measures as covariates in models",
    "\n## Statistical Notes",
    "\n- All chi-squared tests assume independence of observations",
    "- T-tests use Welch's correction for unequal variances",
    "- P-values < 0.05 are considered statistically significant",
    "- Multiple testing corrections were not applied to maintain sensitivity to potential biases"
  )
  
  return(report)
}

